pipeline{
    agent{
        label any
    }
    tools {
        /* Place the tools that will be used in this pipeline */
        // Example: nodejs "name"
    }
    stages{
        stage("SonnarQube Analysis"){
            steps{
                echo "running sonar-scanner..."
            }
        }

        stage("Quality Gates"){
            steps{
                sleep(60) // Should wait aprox. 1 minute
                echo "Waiting for Sonnar Scanner results and verify Quality Gates"
            }
        }

        stage("Postman - Newman"){
            steps{
                sleep(60) // Should wait aprox. 1 minute
                echo "The tests will be run in postman newman"
            }
        }

        stage("Cypress"){
            steps{
                sleep(60) // Should wait aprox. 1 minute
                echo "The tests will be run in cypress"
            }
        }

        stage("Jmeter"){
            steps{
                sleep(60) // Should wait aprox. 1 minute
                echo "Will run load and stress tests in JMeter"
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
